### ISSUE TITLE
Unable to set the time in iOS 17.

### ISSUE THREAD

**Issue by rajhraval** [shinydevelopment/SimulatorStatusMagic#118]
I am using the updated code on `master`.

Console still prints up
`Unsupported use of UIStatusBarSever SPI outside of SpringBoard. Use System Status APIs instead`.

I had a look over the #115 but still I wasn't able to set the time.
Are there any specific instructions for it?

I am using Xcode 15.

**Comment by chrisvasselli** [comment]
Sorry for the confusion! The updated instructions are in the README:

> [1) Injecting into Springboard (Required on iOS 17+)](https://github.com/shinydevelopment/SimulatorStatusMagic#1-injecting-into-springboard-required-on-ios-17)
> tl;dr Running build_and_inject.sh booted will apply a default status bar to the running simulator. Replace "booted" with a simulator UDID to target a specific simulator.
> 
> As of iOS 17, the API used by SimulatorStatusMagic is not accessible to processes other than Springboard. So, in iOS 17+ we need to inject SimulatorStatusMagic into the Springboard process itself, which we do by building it as a dynamic library, and then updating Springboard's launchd configuration to load our dynamic library.
> 
> Running build_and_inject.sh will do all of this for you. If you want to change anything about the values used in the status bar, you will need to update DynamicLibrary/main.m.

Let me know if you have any trouble, I'll update the instructions if needed!

**Comment by rajhraval** [comment]
It works!
For beginners, It would be great if there were the steps to instructions the `.sh` file.
I too for a minute had to check how to run .sh file 😅

Thank you for the help!

**Comment by chrisvasselli** [comment]
@rajhraval that's good feedback, I'll update the readme, thanks!
