### ISSUE TITLE
Integration with fastlane

### ISSUE THREAD

**Issue by sebastianpopp** [shinydevelopment/SimulatorStatusMagic#121]
I'm using fastlane to take my screenshots for different devices and locales on iOS 17.0.1. Do you think it can be possible to integrate SimulatorStatusMagic with fastlane somehow?  
I've tried disabling the `override_status_bar` option in fastlane and running `./build_and_inject.sh booted` before running fastlane and it seems to be working for a few screenshots, but not all.

**Comment by MortenGregersen** [comment]
The simulator has to be running before running the script. You could (in you Fastfile) use `simctl` to launch the simulators, run the script and then run `snapshot`
