### ISSUE TITLE
Cocoapod spec requires ios 7.0

### ISSUE THREAD

**Issue by PezHead** [shinydevelopment/SimulatorStatusMagic#13]
I was trying to install the SimulatorStatusMagic pod into a project that targets iOS 6.1, but got an error that it requires 7.0. The podspec in this repo says 6.0, but the Cocoapod spec seems to require 7.0. Hopefully 6.0 is supported and it just didn't get pushed up :]

**Comment by hiltonc** [comment]
I've been referencing it like this:

    # Using a specific commit for iOS 6.1 compatibility
    pod 'SimulatorStatusMagic', :git => 'https://github.com/shinydevelopment/SimulatorStatusMagic.git', :commit => '8b3458d8f068b9e0e70f71df7f3bdd68f04c288f'

An actual podspec update should happen to support this, but I didn't want to bother the maintainer.

**Comment by daveverwer** [comment]
Apologies, I hadn't realised I didn't do an official release after merging the PR that included 6.0 support. I'll do it now.

**Comment by PezHead** [comment]
Oh, no worries at all. Thanks for the quick response from both of you.

**Comment by daveverwer** [comment]
Done!
