### ISSUE TITLE
Doesn't work in any ios 8.3 simulator

### ISSUE THREAD

**Issue by dpletter** [shinydevelopment/SimulatorStatusMagic#16]
Works from XCode 6.3 in the 8.1 simulators, but not in the 8.3 simulators.  Makes a black box show up on the header, doesn't update time, deosn't remove carrier name.

**Comment by daveverwer** [comment]
Thanks very much for reporting this. I've just checked and sure enough it seems like this is broken in the iOS 8.3 simulator. We don't have a lot of time free to look at this right now but if anyone fancies taking a crack at it, pull requests are very welcome.

Dave

**Comment by CraigSiemens** [comment]
I found a solution but it will cause it to stop working on simulators < 8.3.

I think I might be able to get it to work on simulators < 8.3 only if the app was not built with the 8.3 SDK. I'll play around with it a bit more and get back to you.

**Comment by daveverwer** [comment]
That's excellent news Craig!

**Comment by hiltonc** [comment]
Do you have a fork with the 8.3 fix? I'd love to use it.

**Comment by CraigSiemens** [comment]
It's all local at the moment.

Basically the `StatusBarRawData` and `StatusBarOverrideData` structs changed just enough to break everything. I've got two possible solutions, just look for some feedback/suggestion on the best choice going forward.

1. Use `#ifdef __IPHONE_8_3` to change which struct definition is used at compile time. The only case where this wont work is when the app is compiled using the 8.3 SDK and run on a simulator < 8.3.
2. Define two different structs and create two versions of `enableOverrides` and `disableOverrides`, one for < 8.3 and one for >= 8.3. This should always work, it just creates a lot of duplicated code.

Right now I'm leaning towards 2, but if anyone knows a way to change struct types at runtime that would definitely simplify things.

**Comment by salConigliaro** [comment]
I'd vote for #2 as well.

Thanks for doing this, Craig!

Sal

On Thu, Apr 9, 2015 at 4:54 PM, Craig Siemens <notifications@github.com>
wrote:

> It's all local at the moment.
>
> Basically the StatusBarRawData and StatusBarOverrideData structs changed
> just enough to break everything. I've got two possible solutions, just look
> for some feedback/suggestion on the best choice going forward.
>
>    1. Use #ifdef __IPHONE_8_3 to change which struct definition is used
>    at compile time. The only case where this wont work is when the app is
>    compiled using the 8.3 SDK and run on a simulator < 8.3.
>    2. Define two different structs and create two versions of
>    enableOverrides and disableOverrides, one for < 8.3 and one for >=
>    8.3. This should always work, it just creates a lot of duplicated code.
>
> Right now I'm leaning towards 2, but if anyone knows a way to change
> struct types at runtime that would definitely simplify things.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shinydevelopment/SimulatorStatusMagic/issues/16#issuecomment-91353956>
> .
>



-- 
Sal Conigliaro,
e design
http://www.erinedesign.com
@sconig
