### ISSUE TITLE
SimulatorStatusMagic for Swift code

### ISSUE THREAD

**Issue by larryonoff** [shinydevelopment/SimulatorStatusMagic#24]
SimulatorStatusMagic doesn't work for Swift project. Please help. What I did wrong?

See what I did below.

Podfile
```ruby
pod 'SimulatorStatusMagic', '~> 1.7', :configurations => ['Debug', 'AdHoc']
```

Bridging-Header.h
```objc
#ifdef SNAPSHOT
    #import <SimulatorStatusMagic/SDStatusBarManager.h>
#endif
```
AppDelegate.swift
```swift
#if SNAPSHOT
    SDStatusBarManager.sharedInstance().enableOverrides()
#endif
```

**Comment by daveverwer** [comment]
What happened? Did you get an error or did it just do nothing?

**Comment by larryonoff** [comment]
Just no errors. I run snapshot tool and it shows my current time. It works when I comment #if and #ifdef

**Comment by daveverwer** [comment]
Seems to work well for me, I just integrated the latest version into a new Swift project and everything works fine. https://github.com/daveverwer/TestStatusBar

**Comment by daveverwer** [comment]
Oh hold on, it works if you comment out your ifdef? :)

Are you defining SNAPSHOT?

**Comment by larryonoff** [comment]
Yes. I define SNAPSHOT. Simply I use default Snapfile setting.
```
custom_build_args "GCC_PREPROCESSOR_DEFINITIONS='$(inherited) SNAPSHOT=1'"
```
In your example you use, what is only iOS 8.0. I still support iOS 7.0 :(.
```swift
import SimulatorStatusMagic
```

**Comment by daveverwer** [comment]
What I'd suggest is that you take that project I just uploaded and convert it to a bridging header, without snapshot and see if you can reproduce the problem. However, given that you said it works without that ifdef, I have a feeling it will work in that project too. 

If it works like that, I don't think it's a problem with SimulatorStatusMagic.

**Comment by larryonoff** [comment]
I don't think that it is SimulatorStatusMagic problem either. Just wanted to know maybe there's some recommendations.

Additional questions. Will Apple reject the app if SimulatorStatusMagic is just imported into the production build?

**Comment by hiltonc** [comment]
`"GCC_PREPROCESSOR_DEFINITIONS='$(inherited) SNAPSHOT=1'"` is for C/Objective-C code. You'll want to use `"OTHER_SWIFT_FLAGS='$(inherited) -DSNAPSHOT=1'"` for Swift code.

**Comment by larryonoff** [comment]
Thanks for explanation. Now I should find how to add it into fastline snapshot. :)

**Comment by larryonoff** [comment]
Here's what I have now and it works very well.

```
custom_build_args "GCC_PREPROCESSOR_DEFINITIONS='$(inherited) SNAPSHOT=1' OTHER_SWIFT_FLAGS='$(inherited) -DSNAPSHOT=1'"
```

@hiltonc is there any way to define ```custom_build_args``` better, e.g. define each GCC_PREPROCESSOR_DEFINITIONS and OTHER_SWIFT_FLAGS on the new line?

**Comment by hiltonc** [comment]
Looks good to me, I don't know how to make it better.

**Comment by larryonoff** [comment]
thanks!
