### ISSUE TITLE
Need help maintaining this, any volunteers?

### ISSUE THREAD

**Issue by daveverwer** [shinydevelopment/SimulatorStatusMagic#41]
I don't have a huge amount of time to maintain this project. Anyone up for helping on a more permanent basis?

@zwaldowski @kenji21 @CraigSiemens maybe? Since you've all submitted PRs with core upgrades for new OS versions in the past.

**Comment by kenji21** [comment]
Hi dave,

Thanks for thinking to me, I don't know if I'll also have enought time to maintain this. iOS 10 will be out shortly, and I didn't have any time to test Xcode 8... maybe "co-maintaining" can be a solution ?

**Comment by juli1quere** [comment]
Hi @daveverwer, 

Do you have any precise feature to develop in mind ?

**Comment by daveverwer** [comment]
No, just maintenance and the inevitable changes that are needed every time a new major version of iOS comes out in beta/release.

**Comment by ZevEisenberg** [comment]
@daveverwer what's involved in maintenance? Do you have any guide for how to develop a version that works against the latest iOS? It's all pretty mystical to me, and if there were some kind of "setting started" guide, I or others may be more likely to contribute.

**Comment by daveverwer** [comment]
There's nothing written up at the moment... Basically it's a matter of extracting the new struct and figuring out if anything has changed and testing it with the new simulators etc...

It's a good idea though, I'll have a go at writing a guide when the iOS 12 beta appears in June.

**Comment by Kjuly** [comment]
So far so good, this's really an awesome framework, appreciate it! 👍 

Do hope Xcode team could also expose a way to achieve such setting in the future, while the QuickTime team did a great job on recording movie from real device.

**Comment by o15a3d4l11s2** [comment]
I will be happy to help. Since iOS 12 public beta is out - has someone tried if everything works as expected there?

**Comment by daveverwer** [comment]
There was already a [pull request](https://github.com/shinydevelopment/SimulatorStatusMagic/pull/64) for iOS 12 that @cysp kindly contributed which worked on beta 1.

I just tried to check that still worked on b4 and I'm getting a unicode error in one of the localisation files when building which is weird. I don't have time to look at it now. However, if you can reproduce that it'd be great to get that fixed!

````
CopyStringsFile /Users/dave/Library/Developer/Xcode/DerivedData/SimulatorStatusMagic-ccfcexedjcyvutgpbyqjoibzonfk/Build/Products/Debug-iphonesimulator/SimulatorStatusMagic.app/de.lproj/Localizable.strings /Users/dave/Development/SimulatorStatusMagic/SimulatorStatusMagic/de.lproj/Localizable.strings (in target: SimulatorStatusMagic)
    cd /Users/dave/Development/SimulatorStatusMagic
    builtin-copyStrings --validate --inputencoding utf-8 --outputencoding binary --outdir /Users/dave/Library/Developer/Xcode/DerivedData/SimulatorStatusMagic-ccfcexedjcyvutgpbyqjoibzonfk/Build/Products/Debug-iphonesimulator/SimulatorStatusMagic.app/de.lproj -- /Users/dave/Development/SimulatorStatusMagic/SimulatorStatusMagic/de.lproj/Localizable.strings

error: could not decode input file using specified encoding: Unicode (UTF-8)
````

Just deleted my DerivedData and I still get it, so it's maybe an issue with b4?

**Comment by cysp** [comment]
Hm. That strings file isn't encoded with utf-8, it's utf-16 with a BOM. 
Perhaps Xcode has become less forgiving of that? Xcode 9.4 appears to run the same command and succeeds.
¯\\_(ツ)_/¯ 
Here's a PR that sets the correct encoding in the project file: https://github.com/shinydevelopment/SimulatorStatusMagic/pull/65 😁 

Interestingly, [the "English" strings file](https://github.com/shinydevelopment/SimulatorStatusMagic/blob/master/SimulatorStatusMagic/en.lproj/Localizable.strings) alongside that one (which is not referenced by the project) actually has German text in it.

**Comment by daveverwer** [comment]
👍 

We should get rid of that "English" strings file too. 😄
