### ISSUE TITLE
Non-public API usage warning

### ISSUE THREAD

**Issue by TimMumsnet** [shinydevelopment/SimulatorStatusMagic#47]
When attempting to upload my app to ITC, I received an email informing me:

> Non-public API usage:
> The app contains or inherits from non-public classes in Frameworks/SimulatorStatusMagiciOS.framework/SimulatorStatusMagiciOS: UIStatusBarServer

I've imported the SimulatorStatusMagic project, added `SimulatorStatusMagiciOS.framework` as an embedded binary. To ensure I don't include the framework in the submission, I only import the framework on the debug config, but I think I'm missing something...

**Comment by kenji21** [comment]
embedding the framework makes it being copied within the folder "YourApp.app/Framework", and so uploaded to ITC
A solution can be to rm -R it in a script build phase after the "embed framework" one, removing it only when:

    if [ "$ACTION" == "install" ] ; then
         rm ....
    fi

**Comment by FelixII** [comment]
@kenji21 's solution worked for me, here's the complete command:

    rm -R ${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/SimulatorStatusMagic.framework

Instead of using the if clause you can also check the box 'Run script only when installing'.

**Comment by TimMumsnet** [comment]
@FelixII - this is perfect, it's submitting without errors now. Thanks!
