### ISSUE TITLE
iOS 10.3

### ISSUE THREAD

**Issue by cherpake** [shinydevelopment/SimulatorStatusMagic#50]
Unfortunately and quite expectedly - with iOS 10.3 it stopped working :(

**Comment by kenji21** [comment]
hmm... are you using the master with PR #49 integrated ? Works fine for me.

**Comment by cherpake** [comment]
I'm using CocoaPods - I guess its outdated there

**Comment by cherpake** [comment]
Updated it manually, still seeing headphones icon :(

https://www.dropbox.com/s/s3pznwjj1wr7z7q/Simulator%20Screen%20Shot%2031%20Mar%202017%2C%2010.56.14.png?dl=0

**Comment by daveverwer** [comment]
Sorry, I hadn't updated the podspec. It's done now and 1.9.4 should be available from Cocoapods.

**Comment by cherpake** [comment]
Thanks for creating this! :)
