### ISSUE TITLE
Battery looks critically low in Xcode 9/iOS 11

### ISSUE THREAD

**Issue by ZevEisenberg** [shinydevelopment/SimulatorStatusMagic#53]
Default status bar (I'm on a desktop Mac):

![before](https://user-images.githubusercontent.com/464574/30249857-bdf34d92-9612-11e7-91ca-c3b672ce0812.png)

After running `SDStatusBarManager.sharedInstance().enableOverrides()`:

![after](https://user-images.githubusercontent.com/464574/30249859-c60ef2ba-9612-11e7-9ea2-b1ac60ae495d.png)

The carrier bars are also semi-transparent, but I'm not sure if that's the default or not because I'm not running the iOS 11 beta on a device will cellular radios.

**Comment by Atrac613** [comment]
Hi, I'm same issue too. (Xcode 9 GM and IOS 11)
But GitHub repo code is works fine!

e.g.
```
pod 'SimulatorStatusMagic', :configurations => ['Debug'], :git => 'https://github.com/shinydevelopment/SimulatorStatusMagic.git'
```

**Comment by daveverwer** [comment]
Sorry, the code had been updated [here](https://github.com/shinydevelopment/SimulatorStatusMagic/pull/52) but I had forgotten to update the CocoaPod spec.

It's Done now!
