### ISSUE TITLE
Clock fails to set on iPhone X

### ISSUE THREAD

**Issue by ZevEisenberg** [shinydevelopment/SimulatorStatusMagic#55]
These two simulators are running the same app under iOS 11 and both have called `SDStatusBarManager.sharedInstance().enableOverrides()`.

<img width="969" alt="screen shot 2017-09-16 at 5 34 08 pm" src="https://user-images.githubusercontent.com/464574/30516185-530ed8dc-9b05-11e7-9864-ef112c088a20.png">

**Comment by Domsware** [comment]
Same problem here.
Xcode 9.0.1

**Comment by eitoball** [comment]
Try with GitHub master like

```
pod 'SimulatorStatusMagic', git: 'https://github.com/shinydevelopment/SimulatorStatusMagic.git'
```

The version on GitHub master (version 2.0.0) seems to have iOS 11 support.

**Comment by ZevEisenberg** [comment]
@eitoball are you testing on the iPhone X simulator? That's the only one where I was having problems.

**Comment by daveverwer** [comment]
Closing as this does appear to work as long as you've updated to at least 2.0 of SimulatorStatusMagic.

**Comment by paulofierro** [comment]
I'm also seeing this problem with the iPhone X simulator using SimulatorStatusMagic 2.1 and Xcode 9.3.
