### ISSUE TITLE
Use in React Native

### ISSUE THREAD

**Issue by serhiipalash** [shinydevelopment/SimulatorStatusMagic#62]
Hi! You have a very useful tool. Do you know is it possible to use it in React Native?

I our RN-project we don't have Podfile or Xcode-project. 

Thanks!

**Comment by daveverwer** [comment]
You can just run the app before you take screenshots, the settings are persisted and you don't need to use the framework.

**Comment by serhiipalash** [comment]
Cool! Everything works. Thanks!
