### ISSUE TITLE
CocoaPods Release

### ISSUE THREAD

**Issue by fishcharlie** [shinydevelopment/SimulatorStatusMagic#70]
Any chance we could get a CocoaPods release for this? Seems like there have been some major changes in regards to Xcode 10 that need to be released on CocoaPods.

**Comment by daveverwer** [comment]
I don't like doing a CocoaPods release when there are still bugs and there are still several things not working with iOS 12, especially with iPad. I'm travelling at the moment so I don't have time to look at these bugs.

In the mean time, you can point your podfile at the master branch. Sorry!
