### ISSUE TITLE
On iPad with iOS 12, the status bar date can’t be overridden

### ISSUE THREAD

**Issue by frankrausch** [shinydevelopment/SimulatorStatusMagic#72]
It would be great if SimulatorStatusMagic could override or hide the iOS 12 status bar date.

<img width="797" alt="screen shot 2018-09-18 at 14 25 36" src="https://user-images.githubusercontent.com/6783714/45687511-4a68e900-bb4f-11e8-9442-6a3cdcc40b2f.png">

Also: Thanks so much for your great work on SimulatorStatusMagic—I’ve been using it for a while and love it!

**Comment by bryanrahn** [comment]
This is what iOS 12 on an iPad shows when put into screenshot mode via QuickTime.

<img width="1064" alt="messages image 1373116591" src="https://user-images.githubusercontent.com/729269/46039985-c07fc980-c0d4-11e8-8619-c2ae7ed52564.png">

**Comment by frankrausch** [comment]
Tuesday, January 9, 2007 👌

**Comment by daveverwer** [comment]
This is now fixed and pushed to CocoaPods as v2.4.

Thanks to @saagarjha for contributing to this!
