### ISSUE TITLE
StatusBar not applied on iOS 13 Simulator

### ISSUE THREAD

**Issue by NickAtGit** [shinydevelopment/SimulatorStatusMagic#85]
![Simulator Screen Shot - iPhone Xs Max - 2019-09-17 at 00 12 05](https://user-images.githubusercontent.com/7500549/64997042-d7b85800-d8df-11e9-8e2a-bd2af79a15c4.png)

The status bar is not being applied on an iOS 13 simulator device. Xcode Version 11.0 (11A419c). The only thing that seems to work are the signal strength bars.

**Comment by guidev** [comment]
+1

**Comment by daveverwer** [comment]
I'm afraid that this project is now deprecated since Xcode 11 includes the new `xcrun simctl status_bar` tool.

I will merge pull requests if you still want to maintain it, but I will not be actively maintaining it anymore.

Dave

**Comment by kenji21** [comment]
hmm, `simctl status_bar` does not allow to change "Carrier" name :/

**Comment by daveverwer** [comment]
This is true, and I hope that Apple adds that in the future as it was always a popular feature request. However, it doesn't change how I feel about the future of this project. I'd be more than happy if someone wanted to continue maintenance of this if there is still a need for it, but `simctl` works well enough for most cases now.

Also, the current version does work on iOS 13 as far as I'm aware thanks to the work of @cysp.

**Comment by kenji21** [comment]
oh, i didn't saw the ios13 branch (from https://github.com/shinydevelopment/SimulatorStatusMagic/pull/80)

Hoping also that Apple add it, until then I will continue to use this library

Using this API to take screenshot (even in Unit test bundle) works: https://developer.apple.com/documentation/xctest/xcuiscreenshotproviding/2897250-screenshot

And our CI shows screenshots via https://github.com/TitouanVanBelle/XCTestHTMLReport to users not having Xcode on their Mac

will have to configure simulators on CI when apple ship the Carrier customisation feature (feedback assistant ticket created) (maybe already available in Xcode 11.1 ?)

Can a "last" release still be pushed (having my cartfile pointing to the ios13 branch isn't really an issue) ?

**Comment by daveverwer** [comment]
I'd be happy to merge the `ios13` branch if you can confirm it's all working well enough. I've opened up a new issue #86 to track that merge. Please report any final issues with the `ios13` branch there.

**Comment by kenji21** [comment]
Time & Carrier (with full bars) are OK, battery percentage is shown on iPhone 8, but network logo isn't, and bluetooth is not (but also doesn't work on a 8 Plus with iOS 12)

**Comment by mindthefrog** [comment]
@daveverwer one thing to consider is that "simctl status_bar" doesn't appear to work properly when the simulator is in a non-english locale. The time (and date on the iPad) are always formatted using the en_US locale. This is a problem for localized screenshots esp. on iPad.

I'll love not having to use SimulatorStatusMagic some day but for now I'm on the ios13 branch.

**Comment by ZevEisenberg** [comment]
I filed FB7668656: **Status bar clock and simctl status_bar don’t respect app language**, if you want to dupe it
