### ISSUE TITLE
One final release before deprecation…

### ISSUE THREAD

**Issue by daveverwer** [shinydevelopment/SimulatorStatusMagic#86]
Since the work for iOS 13 has already been done by @cysp, and the product of that work is still needed (see #85) @kenji21 has suggested we do one final release of this project so this issue is to track that final merge.

Of course, knowing open-source projects they rarely go as intended and so I'd bet this isn't even nearly going to be the last merge! 😂

**Comment by babbage** [comment]
Just commenting to say—thanks team for your awesome work on this project over the years. Hugely appreciated from the day I discovered it until it achieved escape velocity in the best possible way. Major [Whuffie](https://en.wikipedia.org/wiki/Down_and_Out_in_the_Magic_Kingdom) for all of you... :)

**Comment by daveverwer** [comment]
Thank you @babbage, appreciate the kind words.

**Comment by kenji21** [comment]
Xcode 11.4 will add a feature I was missing from SSM : 

```
 simctl status_bar now allows changing the operator (carrier) name. (54162823) (FB6985308)
```

**Comment by daveverwer** [comment]
Yep, it really does everything needed now. I think the best replacement for this project now is probably [ControlRoom](https://github.com/twostraws/ControlRoom)

**Comment by mindthefrog** [comment]
As far as I can tell, as of Xcode 11.4, "xcrun simctl status_bar override" does not format the date and time in the simulator's locale. This is an issue for localized screenshots, esp on iPad. If anyone knows of a solution, please post. It's the one issue keeping me on the ios13 branch of this (wonderful) project.

**Comment by clindsay** [comment]
@mindthefrog Yep, this is why I am still using this project as well. I filed a bug with Apple back in October, still not resolved unfortunately. FB7384669

**Comment by daveverwer** [comment]
I know this thread was from last year, but there are now three PRs in for iOS 14 support, kindly submitted by @thezonie and @nrbrook.

I'd love to bring one (or preferably more!) of you on as additional maintainers.

`simctl` does everything I need, and so I'm not particularly invested in merging these PRs myself. I'd love to give someone else commit access, if they'd like to get those iOS 14/Xcode 12 PRs through out of the door, and continue it for as long as it's useful to you.

Please reply here, and we can discuss it.

**Comment by nrbrook** [comment]
Hi @daveverwer, yes I would be happy to help maintain. I've not dug into the code but I made project changes to support the latest xcode and fix warnings.

**Comment by daveverwer** [comment]
That's great news, thanks @nrbrook! Anyone else want to join Nick? I'd love it if there were two people so you could review each other's code, etc...

**Comment by chrisvasselli** [comment]
@daveverwer @nrbrook sure, I'm happy to help maintain. I've spent some time digging into the code for my PR https://github.com/shinydevelopment/SimulatorStatusMagic/pull/87 so I think I have a good idea of what needs to happen for each major iOS release.

**Comment by daveverwer** [comment]
That's such great news, thank you both! What I'd suggest is that you make a new branch directly on this repo with the best of both of the PRs in it so you can both commit to it. I'll give you both write access now.

I'll need to do the final release to CocoaPods, and I'm more than happy to do that. Ping me if you need anything.

**Comment by chrisvasselli** [comment]
@nrbrook looks like https://github.com/shinydevelopment/SimulatorStatusMagic/pull/90 is https://github.com/shinydevelopment/SimulatorStatusMagic/pull/88 plus the changes suggested by Xcode. Maybe we should start by going ahead and merging https://github.com/shinydevelopment/SimulatorStatusMagic/pull/88, and then rebasing https://github.com/shinydevelopment/SimulatorStatusMagic/pull/90 on top of it so we can consider the Xcode changes separately?

**Comment by nrbrook** [comment]
Yep, if you want to do this go ahead, or after merging https://github.com/shinydevelopment/SimulatorStatusMagic/pull/88 I can rebase my PR

**Comment by chrisvasselli** [comment]
@nrbrook I tested #88 and merged it. Go ahead and rebase whenever you have a chance. Then we can move towards getting the ios13 branch merged into master..

**Comment by nrbrook** [comment]
I think we can probably merge it now?

**Comment by chrisvasselli** [comment]
@nrbrook yep, I think we can go ahead and merge it now.

**Comment by daveverwer** [comment]
Thank you both so much for your efforts with this. They are very much appreciated. ❤️

I just released it to CocoaPods.

```
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  SimulatorStatusMagic (2.5) successfully published
 📅  March 17th, 16:14
 🌎  https://cocoapods.org/pods/SimulatorStatusMagic
 👍  Tell your friends!
--------------------------------------------------------------------------------
```

**Comment by nrbrook** [comment]
Mostly @chrisvasselli's work, sorry for my delay in reviewing, cheers!

**Comment by chrisvasselli** [comment]
@nrbrook no worries! Thanks for the quick turnaround on all my PR's!
